# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['build_future_maxmin_idx_ds', 'hello']

# %% ../nbs/00_core.ipynb 4
def build_future_maxmin_idx_ds(stock_code, maxmin_period=90):
    hist = ak.stock_zh_index_daily(symbol=stock_code)
    print(len(hist))
    ds = hist.iloc[:-maxmin_period, :]
    print(len(ds))
    
    future_max = [None] * (len(ds))
    future_max_pos = [None] * (len(ds))
    future_min = [None] * (len(ds))
    future_min_pos = [None] * (len(ds))
    
    for pointer in np.arange(len(hist)-maxmin_period):
        future_segment = hist.iloc[pointer+1:pointer+maxmin_period, :]
        
        future_max[pointer] = future_segment['high'].max()
        future_max_pos[pointer] = future_segment['high'].argmax()
        
        future_min[pointer] = future_segment['low'].min()
        future_min_pos[pointer] = future_segment['low'].argmin()     
    
    ds['future_range_max'] = future_max
    ds['future_range_max_pos'] = future_max_pos
    
    ds['future_range_min'] = future_min
    ds['future_range_min_pos'] = future_min_pos
    
    
    return ds
    
    

# %% ../nbs/00_core.ipynb 8
def hello(): 
    print('Hello, StreamTSAI!')
